const $ = s => document.querySelector(s);
const fields = {brand:$("#brandInput"), email:$("#emailInput"), product:$("#productInput")};
const nav=$("#pageNav"), title=$("#pageTitle"), kind=$("#pageKind"), preview=$("#preview"), codebox=$("#sourceBox"), copyBtn=$("#copyBtn"), msg=$("#message"), toast=$("#toast");
let pages={}, current="";

function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));}
function val(){return {brand:fields.brand.value.trim(),email:fields.email.value.trim(),product:fields.product.value.trim()};}
function fill(text){const v=val();return text.replaceAll("{{BRAND}}",v.brand||"[BRAND]").replaceAll("{{EMAIL}}",v.email||"[SUPPORTMAIL]").replaceAll("{{PRODUCT}}",v.product||"[PRODUKT]");}
function inline(s){let x=esc(s);x=x.replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>");x=x.replace(/\[(.+?)\]\((https?:\/\/[^\s)]+)\)/g,'<a href="$2" target="_blank" rel="noopener">$1</a>');return x;}
function toHtml(md){const lines=md.replace(/\r/g,"").split("\n");let out="",list=false;const close=()=>{if(list){out+="</ul>";list=false;}};for(const line of lines){const t=line.trim();if(!t){close();continue;}const h=t.match(/^(#{1,4})\s+(.+)$/);if(h){close();out+=`<h${h[1].length}>${inline(h[2])}</h${h[1].length}>`;continue;}if(t.startsWith("- ")||t.startsWith("• ")){if(!list){out+="<ul>";list=true;}out+=`<li>${inline(t.slice(2))}</li>`;continue;}close();out+=`<p>${inline(t)}</p>`;}close();return out;}
function plain(md){return md.replace(/\*\*/g,"").replace(/\[(.+?)\]\((https?:\/\/[^\s)]+)\)/g,"$1: $2").replace(/^#{1,4}\s+/gm,"").trim();}
function save(){localStorage.setItem("store_builder_v3",JSON.stringify(val()));render();}
function load(){try{const v=JSON.parse(localStorage.getItem("store_builder_v3")||"{}");fields.brand.value=v.brand||"";fields.email.value=v.email||"";fields.product.value=v.product||"";}catch{}}
function showToast(t){toast.textContent=t;toast.classList.add("show");clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove("show"),1500);}
function warning(content){const v=val(),issues=[];if(!v.brand||!v.email||!v.product)issues.push("Fyll i Brand, Supportmail och Produkt.");if(/Ryggro|kundservice\.ryggro/i.test(content))issues.push("Gamla Ryggro-uppgifter hittades.");if(issues.length){msg.className="message show";msg.textContent=issues.join(" ");}else{msg.className="message good";msg.textContent="✓ Klar att kopiera";}}
function renderNav(){nav.innerHTML="";Object.keys(pages).forEach(name=>{const b=document.createElement("button");b.type="button";b.className="tab"+(name===current?" active":"");b.textContent=name;b.onclick=()=>{current=name;renderNav();render();};nav.appendChild(b);});}
function render(){const item=pages[current];if(!item)return;const content=fill(item.content);title.textContent=current;warning(content);if(item.kind==="html-source"){kind.textContent="SHOPIFY · HTML";preview.style.display="none";codebox.style.display="block";codebox.value=content;copyBtn.textContent="Kopiera HTML";}else{kind.textContent="SHOPIFY-SIDA";preview.style.display="block";codebox.style.display="none";preview.innerHTML=toHtml(content);copyBtn.textContent="Kopiera";}}
async function copyFallback(text){try{await navigator.clipboard.writeText(text);}catch{const t=document.createElement("textarea");t.value=text;document.body.appendChild(t);t.select();document.execCommand("copy");t.remove();}}
async function copy(){const v=val();if(!v.brand||!v.email||!v.product){showToast("Fyll i de tre fälten först");return;}const item=pages[current],content=fill(item.content);if(/Ryggro|kundservice\.ryggro/i.test(content)){showToast("Gamla uppgifter finns kvar");return;}try{if(item.kind==="html-source"){await copyFallback(content);}else{const h=toHtml(content),p=plain(content);if(window.ClipboardItem&&navigator.clipboard.write){await navigator.clipboard.write([new ClipboardItem({"text/html":new Blob([h],{type:"text/html"}),"text/plain":new Blob([p],{type:"text/plain"})})]);}else await copyFallback(p);}showToast("Kopierat ✓");}catch{await copyFallback(item.kind==="html-source"?content:plain(content));showToast("Kopierat ✓");}}
Object.values(fields).forEach(x=>x.addEventListener("input",save));copyBtn.addEventListener("click",copy);
(async()=>{const r=await fetch("pages.json",{cache:"no-store"});pages=await r.json();current=Object.keys(pages)[0];load();renderNav();render();})().catch(()=>{msg.className="message show";msg.textContent="Kunde inte starta. Kör appen via Python-servern.";});
